---

- name: install nfs server
  action: apt pkg=nfs-kernel-server state=present update_cache=yes
  become: yes
  when: is_debian_or_ubuntu
  tags:
    -nfs

- name: install nfs client
  action: apt pkg=nfs-common state=present
  become: yes
  when: is_debian_or_ubuntu
  tags:
    -nfs

- name: ensure nfs service is running
  action: service name={{item}} state=started
  when: is_debian_or_ubuntu
  tags:
    - nfs
  with_items:
    - nfs-kernel-server